image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
      gp sync-done install
    command: npm run start
  - init: gp sync-await install
    command: npx cypress run --spec **/sanity.js
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
